#define TOK_IF 1
#define TOK_ELSE 2
#define TOK_WHILE 3
#define TOK_AUTO 4
#define TOK_BREAK 5
#define TOK_CASE 6
#define TOK_CONST 7
#define TOK_CONTINUE 8
#define TOK_DEFAULT 9
#define TOK_DO 10
#define TOK_DOUBLE 11
#define TOK_ENUM 12
#define TOK_EXTERN 13
#define TOK_FLOAT 14
#define TOK_FOR 15
#define TOK_INT 16
#define TOK_LONG 17
#define TOK_RETURN 18
#define TOK_SHORT 19
#define TOK_SIGNED 20
#define TOK_SIZEOF 21
#define TOK_STATIC 22
#define TOK_STRUCT 23
#define TOK_SWITCH 24
#define TOK_VOID 25
#define TOK_ID 26
#define TOK_MAIN 27
#define TOK_PRINTF 28